nodeLinker: node-modules

packageExtensions:
  'iconoir-react-native@*':
    peerDependencies:
      react: '>=18.0.0'
      react-native: '>=0.70.0'
  '@tamagui/core@*':
    peerDependenciesMeta:
      react:
        optional: false
      react-native:
        optional: false
