export {
  DisplayStandard,
  DisplayStandardSemibold,
  DisplaySmall,
  DisplaySmallSemibold,
  TitleLarge,
  TitleLargeSemibold,
  TitleStandard,
  TitleStandardSemibold,
  TitleSmall,
  TitleSmallSemibold,
  BodyLarge,
  BodyLargeSemibold,
  BodyStandard,
  BodyStandardSemibold,
  BodySmall,
  BodySmallSemibold,
  LabelStandard,
  LabelStandardBold,
  LabelSmall,
  LabelSmallRegular,
  LabelSmallBold,
  LabelTiny,
  LabelTinyBold,
} from './Typography';
