trigger: none

resources:
  repositories:
    - repository: templates
      type: git
      name: Templates_CI_CD
      ref: refs/heads/superapp

parameters:
  - name: serviceVersion
    displayName: 'Versão do Serviço'
    type: string
    default: '0.0.1'

variables:
  - name: BUILD_VERSION
    value: '${{ parameters.serviceVersion }}'
  - name: INCREMENT_VERSION
    value: $[counter(variables['BUILD_VERSION'], 1)]
  - name: FINAL_VERSION
    value: '${{ parameters.serviceVersion }}.$(INCREMENT_VERSION)'

extends:
  template: solutions/rn-module-azure-solution.yaml@templates
  parameters:
    serviceVersion: '${{ parameters.serviceVersion }}'
    nodeVersion: '20.x'
    yarnVersion: '4.9.2'
    moduleName: 'storybook-rn'
    buildPoolName: 'ubuntu-latest'
    scanPoolName: 'ads-mobilidade-dev'
    workDir: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/apps/storybook-rn'
    ambientes:
      - nome: 'des'
        deployPoolName: 'ads-mobilidade-dev'
        variableGroup: 'VG_RN_MODULE_DES'
        serviceConnection: 'sc-mobilidade-dev-ComunidadeCanaisMobile'
        buildType: 'storybook-generate'
      # - nome: 'qa'
      #   deployPoolName: 'ads-sinbm-qa'
      #   variableGroup: 'VG_SERVICES_QA'
      #   variableGroupInfra: 'VG_SERVICES_INFRA_QA'
      #   azureServiceConnection: 'sc-sinbm-plt'
      # - nome: 'tqs'
      #   deployPoolName: 'ads-sinbm-tqs'
      #   variableGroup: 'VG_SERVICES_TQS'
      #   variableGroupInfra: 'VG_SERVICES_INFRA_TQS'
      #   azureServiceConnection: 'sc-sinbm-plt'
      # - nome: 'prd'
      #   deployPoolName: 'ads-sinbm-prd'
      #   variableGroup: 'VG_SERVICES_PRD'
      #   variableGroupInfra: 'VG_SERVICES_INFRA_PRD'
      #   azureServiceConnection: 'sc-sinbm-prd'
