export const typography = {
  displayStandard: {
    fontFamily: '$heading',
    fontSize: '$larger',
    fontWeight: '$400',
    lineHeight: 44,
    letterSpacing: '$standard',
  },
  displayStandardSemibold: {
    fontFamily: '$heading',
    fontSize: '$larger',
    fontWeight: '$600',
    lineHeight: 44,
    letterSpacing: '$standard',
  },
  displaySmall: {
    fontFamily: '$heading',
    fontSize: '$large',
    fontWeight: '$400',
    lineHeight: 40,
    letterSpacing: '$standard',
  },
  displaySmallSemibold: {
    fontFamily: '$heading',
    fontSize: '$large',
    fontWeight: '$600',
    lineHeight: 40,
    letterSpacing: '$standard',
  },
  titleLarge: {
    fontFamily: '$heading',
    fontSize: '$medium',
    fontWeight: '$400',
    lineHeight: 36,
    letterSpacing: '$standard',
  },
  titleLargeSemibold: {
    fontFamily: '$heading',
    fontSize: '$medium',
    fontWeight: '$600',
    lineHeight: 36,
    letterSpacing: '$standard',
  },
  titleStandard: {
    fontFamily: '$heading',
    fontSize: '$small',
    fontWeight: '$400',
    lineHeight: 32,
    letterSpacing: '$standard',
  },
  titleStandardSemibold: {
    fontFamily: '$heading',
    fontSize: '$small',
    fontWeight: '$600',
    lineHeight: 32,
    letterSpacing: '$standard',
  },
  titleSmall: {
    fontFamily: '$heading',
    fontSize: '$smaller',
    fontWeight: '$400',
    lineHeight: 28,
    letterSpacing: '$standard',
  },
  titleSmallSemibold: {
    fontFamily: '$heading',
    fontSize: '$smaller',
    fontWeight: '$600',
    lineHeight: 28,
    letterSpacing: '$standard',
  },
  bodyLarge: {
    fontFamily: '$body',
    fontSize: '$tiny',
    fontWeight: '$400',
    lineHeight: 28,
    letterSpacing: '$extended',
  },
  bodyLargeSemibold: {
    fontFamily: '$body',
    fontSize: '$tiny',
    fontWeight: '$600',
    lineHeight: 28,
    letterSpacing: '$extended',
  },
  bodyStandard: {
    fontFamily: '$body',
    fontSize: '$micro',
    fontWeight: '$400',
    lineHeight: 24,
    letterSpacing: '$extended',
  },
  bodyStandardSemibold: {
    fontFamily: '$body',
    fontSize: '$micro',
    fontWeight: '$600',
    lineHeight: 24,
    letterSpacing: '$extended',
  },
  bodySmall: {
    fontFamily: '$body',
    fontSize: '$nano',
    fontWeight: '$400',
    lineHeight: 22,
    letterSpacing: '$broad',
  },
  bodySmallSemibold: {
    fontFamily: '$body',
    fontSize: '$nano',
    fontWeight: '$600',
    lineHeight: 22,
    letterSpacing: '$broad',
  },
  labelStandard: {
    fontFamily: '$body',
    fontSize: '$micro',
    fontWeight: '$500',
    lineHeight: 24,
    letterSpacing: '$loose',
  },
  labelStandardBold: {
    fontFamily: '$body',
    fontSize: '$micro',
    fontWeight: '$700',
    lineHeight: 24,
    letterSpacing: '$loose',
  },
  labelSmall: {
    fontFamily: '$body',
    fontSize: '$nano',
    fontWeight: '$500',
    lineHeight: 20,
    letterSpacing: '$airy',
  },
  labelSmallRegular: {
    fontFamily: '$body',
    fontSize: '$nano',
    fontWeight: '$400',
    lineHeight: 16,
    letterSpacing: '$standard',
  },
  labelSmallBold: {
    fontFamily: '$body',
    fontSize: '$nano',
    fontWeight: '$700',
    lineHeight: 20,
    letterSpacing: '$airy',
  },
  labelTiny: {
    fontFamily: '$body',
    fontSize: '$quark',
    fontWeight: '$500',
    lineHeight: 16,
    letterSpacing: '$extended',
  },
  labelTinyBold: {
    fontFamily: '$body',
    fontSize: '$quark',
    fontWeight: '$700',
    lineHeight: 16,
    letterSpacing: '$extended',
  },
} as const;

export type Typography = keyof typeof typography;
