trigger: none

resources:
  repositories:
    - repository: templates
      type: git
      name: Templates_CI_CD
      ref: refs/heads/RN-LIBS-YAML

parameters:
  - name: serviceVersion
    displayName: 'Versão do Serviço'
    type: string
    default: '0.0.1'

variables:
  - group: VG_SERVICES_SHARED
  - name: BUILD_VERSION
    value: ${{ parameters.serviceVersion }}
extends:
  template: solutions/rn-lib-azure-solution.yaml@templates
  parameters:
    serviceVersion: '${{ parameters.serviceVersion }}'
    moduleName: 'superapp-caixa/dsc-library'
    workDir: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/packages/ui-components'
    libPrefix: '--prefix packages/ui-components'
    ambientes:
      - nome: 'snapshot'
      - nome: 'stable'
