import { create } from 'storybook/theming/create';

export default create({
  base: 'light',
  brandTitle: 'CAIXA Design System - React Native',
  brandImage: './images/logo_dsc.png',
  brandTarget: '_self',
  appBg: '#F0F2F2',
  appContentBg: '#FFFFFF',
  appPreviewBg: '#FFFFFF',
  appBorderColor: '#D0E0E3',
  appBorderRadius: 4,
  fontBase: '"Roboto", "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  fontCode: 'monospace',
  textColor: '#404B52',
  textInverseColor: 'green',
  barTextColor: '#64747A',
  barSelectedColor: '#22292E',
  barHoverColor: '#22292E',
  barBg: '#F0F2F2',
  inputBg: '#ffffff',
  inputBorder: '#9EB2B8',
  inputTextColor: '#22292E',
  inputBorderRadius: 4,
  colorPrimary: '#33A0FF',
  colorSecondary: '#33A0FF',
  textMutedColor: '#64747A',
  buttonBg: '#F0F2F2',
  buttonBorder: '#D0E0E3',
  booleanBg: '#F0F2F2',
  booleanSelectedBg: '#E3EBEB',
});
